### ISSUE TITLE
Also cancel remaining promises

### ISSUE THREAD

**Issue by fregante** [sindresorhus/p-race#4]
It kind of irks me that the default for races is to just let everything continue even when the race ended.

What do you think about also calling `.cancel` to the promises that are running?

**Comment by sindresorhus** [comment]
I'm not sure I want to continue adding support for the `p-cancelable` way. It seems the ecosystem is moving to use `AbortController`. Is there any way we could support `AbortController` for this?

**Comment by fregante** [comment]
😁 https://github.com/sindresorhus/p-cancelable/issues/29

**Comment by fregante** [comment]
I suppose that the 2 could actually just be combined here, without extending `p-cancelable`

```js
new pRace([
	signal => fetch('/api', {signal}),
	signal => setTimeout(10, {signal}),
])
```

**Comment by fregante** [comment]
Or

```js
new pRace(signal => [
	fetch('/api', {signal}),
	setTimeout(10, {signal}),
])

**Comment by fregante** [comment]
Also shortcuttable to:

```js
new pRace([
	[fetch, '/api'],
	[setTimeout, 10],
])
```

But this has a few drawbacks and some errors would be silent

**Comment by sindresorhus** [comment]
> new pRace(signal => [
	fetch('/api', {signal}),
	setTimeout(10, {signal}),
])

I like this one.
